Add apikey authenticator
IBM/dotnet-sdk-core pull request #46
Opened 2021-10-12 05:42 UTC by nan2iz

2021-10-12 13:31 UTC, mediumTaj reviewed
just some questions after a quick readthrough nan

2021-10-12 13:31 UTC, mediumTaj commented on src/IBM.Cloud.SDK.Core/Authentication/CloudPakForData/CloudPakForDataAuthenticator.cs
> +        private const string ApikeyKey = "api_key";
Any way we can think of better names for these constants? Not a huge deal, just a nit - probably mostly the ApikeyKey, hah. Here are some constants in the Authenticator base class
https://github.com/IBM/dotnet-sdk-core/blob/main/src/IBM.Cloud.SDK.Core/Authentication/Authenticator.cs#L27-L44

2021-10-12 13:31 UTC, mediumTaj commented on src/IBM.Cloud.SDK.Core/Authentication/CloudPakForData/CloudPakForDataAuthenticator.cs
> +                List<KeyValuePair<string, string>> content = new List<KeyValuePair<string, string>>();
Any reason why we are not using a `Dictionary<string, string>` here?

2021-10-12 13:31 UTC, mediumTaj commented on src/IBM.Cloud.SDK.Core/Authentication/CloudPakForData/CloudPakForDataAuthenticator.cs
> +                throw new ArgumentNullException("The Password or Apikey property is required but was not specified.");
Should we throw this error message in the base class? 
https://github.com/IBM/dotnet-sdk-core/blob/main/src/IBM.Cloud.SDK.Core/Authentication/Authenticator.cs#L46-L48

2021-10-12 13:31 UTC, mediumTaj commented on src/IBM.Cloud.SDK.Core/Authentication/CloudPakForData/CloudPakForDataTokenResponse.cs
> -        public string AccessToken { get; set; }
wow they removed all this from the response?!? ugh

2021-10-12 16:00 UTC, kevinkowa reviewed
It looks good, just a comment

2021-10-12 16:00 UTC, kevinkowa commented on test/IBM.Cloud.SDK.Core.Tests/CloudPak4DataAuthTests.cs
> +        public void TestConstructionApikeyRequried()
possible typo on the name of the method

2021-10-13 08:30 UTC, nan2iz commented on src/IBM.Cloud.SDK.Core/Authentication/CloudPakForData/CloudPakForDataAuthenticator.cs
> +                List<KeyValuePair<string, string>> content = new List<KeyValuePair<string, string>>();
For this one I followed `IamAuthenticator` to create the request type `application/x-www-form-urlencoded`

Let me know if there is a better way to do this as well. Thank you

https://github.com/IBM/dotnet-sdk-core/blob/main/src/IBM.Cloud.SDK.Core/Authentication/Iam/IamAuthenticator.cs#L178

2021-10-13 08:33 UTC, nan2iz commented on src/IBM.Cloud.SDK.Core/Authentication/CloudPakForData/CloudPakForDataAuthenticator.cs
> +                throw new ArgumentNullException("The Password or Apikey property is required but was not specified.");
Initial thought I was thinking about updating the Authenticator file with the new message as well. But this error message is really specific for this case, so I decided to just update as raw message here.

For this case, we want the users to provide either `password` or `apikey`. So I'm not sure if we should create a template like `{0} or {1} is required ....` or just use raw message here.
 
Please let me know if which way that our team prefer.

2021-10-13 08:34 UTC, nan2iz commented on src/IBM.Cloud.SDK.Core/Authentication/CloudPakForData/CloudPakForDataTokenResponse.cs
> -        public string AccessToken { get; set; }
Yes, based on the document. Only 3 properties returned from the request. 😸 

https://cloud.ibm.com/apidocs/cloud-pak-data#getauthorizationtoken-response

2021-10-13 08:34 UTC, nan2iz commented on test/IBM.Cloud.SDK.Core.Tests/CloudPak4DataAuthTests.cs
> +        public void TestConstructionApikeyRequried()
Ok. Will fix it. Thank you

2021-10-13 08:37 UTC, nan2iz commented on src/IBM.Cloud.SDK.Core/Authentication/CloudPakForData/CloudPakForDataAuthenticator.cs
> +        private const string ApikeyKey = "api_key";
Okay. By the way, I'm really not sure how to name these constants. 

These are the keys that we provides on the body for post request to this endpoint. 
Do you mind giving me example how to name one of the constants? Thank you 😸 

 https://cloud.ibm.com/apidocs/cloud-pak-data#get-authorization-token

2021-10-13 14:43 UTC, mediumTaj commented on src/IBM.Cloud.SDK.Core/Authentication/CloudPakForData/CloudPakForDataAuthenticator.cs
> +                List<KeyValuePair<string, string>> content = new List<KeyValuePair<string, string>>();
lol this probably comes from me translating Java to .NET. Its fine if it works!

2021-10-13 14:45 UTC, kevinkowa commented on src/IBM.Cloud.SDK.Core/Authentication/CloudPakForData/CloudPakForDataAuthenticator.cs
> +                throw new ArgumentNullException("The Password or Apikey property is required but was not specified.");
I vote for the template, just to keep it consistent with other authenticators

2021-10-13 14:48 UTC, mediumTaj commented on src/IBM.Cloud.SDK.Core/Authentication/CloudPakForData/CloudPakForDataAuthenticator.cs
> +                throw new ArgumentNullException("The Password or Apikey property is required but was not specified.");
Maybe you can use
```
throw new ArgumentNullException(string.Format(ErrorMessagePropMissing, "password or apikey"));
```

>The password or apikey property is required but was not specified.

2021-10-13 14:50 UTC, mediumTaj commented on src/IBM.Cloud.SDK.Core/Authentication/CloudPakForData/CloudPakForDataAuthenticator.cs
> +        private const string ApikeyKey = "api_key";
maybe it could be `KeyUsername`, `KeyPassword`, `KeyApikey`? what do you think?

2021-10-13 15:09 UTC, nan2iz commented on src/IBM.Cloud.SDK.Core/Authentication/CloudPakForData/CloudPakForDataAuthenticator.cs
> +                throw new ArgumentNullException("The Password or Apikey property is required but was not specified.");
Ah. Smart, I did not think if it before! Will update it. Thanks

2021-10-13 20:53 UTC, mediumTaj commented
Also need to check on CI here

2021-10-18 15:23 UTC, mediumTaj commented on appveyor.yml
> +    nodejs_version: 15.6.0
FYI i made this change in another PR for core so it matches the .NET SDK node version
https://github.com/IBM/dotnet-sdk-core/pull/47/commits/b42296729f5fc380cc7ea1520d1ae5dd952b5697

2021-10-18 15:23 UTC, mediumTaj commented on src/IBM.Cloud.SDK.Core/Authentication/CloudPakForData/CloudPakForDataAuthenticator.cs
> +            Init(url, username, password, apikey, disableSslVerification, headers);
@nan2iz did you get anywhere with the builder/fluent pattern for this?

2021-10-18 18:08 UTC, mediumTaj requested changes
I threw some suggestions in here for consistency

2021-10-18 18:08 UTC, mediumTaj commented on src/IBM.Cloud.SDK.Core/Authentication/CloudPakForData/CloudPakForDataAuthenticator.cs
> +            Init(url, username, password, apikey, disableSslVerification, headers);
I think if the builder pattern works, I dont think we need the 2nd overload.

2021-10-18 18:08 UTC, mediumTaj commented on src/IBM.Cloud.SDK.Core/Authentication/CloudPakForData/CloudPakForDataAuthenticator.cs
> +            this.Url = url;
```suggestion
            Url = url;
```

2021-10-18 18:08 UTC, mediumTaj commented on src/IBM.Cloud.SDK.Core/Authentication/CloudPakForData/CloudPakForDataAuthenticator.cs
> +            this.Username = username;
```suggestion
            Username = username;
```

2021-10-18 18:08 UTC, mediumTaj commented on src/IBM.Cloud.SDK.Core/Authentication/CloudPakForData/CloudPakForDataAuthenticator.cs
> +        public CloudPakForDataAuthenticator setPassword(string password)
```suggestion
        public CloudPakForDataAuthenticator SetPassword(string password)
```

2021-10-18 18:08 UTC, mediumTaj commented on src/IBM.Cloud.SDK.Core/Authentication/CloudPakForData/CloudPakForDataAuthenticator.cs
> +            this.Password = this.Password;
```suggestion
            Password = password;
```

2021-10-18 18:08 UTC, mediumTaj commented on src/IBM.Cloud.SDK.Core/Authentication/CloudPakForData/CloudPakForDataAuthenticator.cs
> +        public CloudPakForDataAuthenticator setApikey(string apikey)
```suggestion
        public CloudPakForDataAuthenticator SetApikey(string apikey)
```

2021-10-18 18:08 UTC, mediumTaj commented on src/IBM.Cloud.SDK.Core/Authentication/CloudPakForData/CloudPakForDataAuthenticator.cs
> +            this.Apikey = this.Apikey;
```suggestion
            Apikey = apikey;
```

2021-10-18 18:08 UTC, mediumTaj commented on src/IBM.Cloud.SDK.Core/Authentication/CloudPakForData/CloudPakForDataAuthenticator.cs
> +            this.DisableSslVerification = disableSslVerification;
```suggestion
            DisableSslVerification = disableSslVerification;
```

2021-10-18 18:08 UTC, mediumTaj commented on src/IBM.Cloud.SDK.Core/Authentication/CloudPakForData/CloudPakForDataAuthenticator.cs
> +            this.Headers = headers;
```suggestion
            Headers = headers;
```

2021-10-18 21:57 UTC, nan2iz commented on src/IBM.Cloud.SDK.Core/Authentication/CloudPakForData/CloudPakForDataAuthenticator.cs
> +            Init(url, username, password, apikey, disableSslVerification, headers);
Okay. I will remove the overload. Thank you

2021-10-18 21:57 UTC, nan2iz commented on src/IBM.Cloud.SDK.Core/Authentication/CloudPakForData/CloudPakForDataAuthenticator.cs
> +            this.Url = url;
Thank you. Will fix it

2021-10-18 23:32 UTC, nan2iz commented on appveyor.yml
> +    nodejs_version: 15.6.0
Okay. I will remove this one. Thank you

2021-10-19 17:01 UTC, nan2iz commented
Note: I will need to wait until this PR https://github.com/IBM/dotnet-sdk-core/pull/47 is merged to the master first.
Since it will fix the build issue. And then I will pull into my branch.

2021-10-19 19:30 UTC, kevinkowa approved these changes
Looks good!

2021-10-20 20:42 UTC, mediumTaj commented on src/IBM.Cloud.SDK.Core/Authentication/CloudPakForData/CloudPakForDataAuthenticator.cs
> +            Init(url, username, password, null, disableSslVerification, headers);
Do we still need apikey in init?

2021-10-20 20:46 UTC, mediumTaj commented on src/IBM.Cloud.SDK.Core/Authentication/CloudPakForData/CloudPakForDataAuthenticator.cs
> +                } else
ah this else should be on a separate line
```suggestion
                } 
                else
```

2021-10-22 20:28 UTC, mediumTaj requested changes
One comment then i think it looks good!

2021-10-22 20:28 UTC, mediumTaj commented on src/IBM.Cloud.SDK.Core/Authentication/CloudPakForData/CloudPakForDataAuthenticator.cs
> +        private void Init(string url, string username, string password, string apikey, bool? disableSslVerification = null, Dictionary<string, string> headers = null)
Do we need default values for password and apikey here? I dont think its guaranteed the values will come back from the config
```suggestion
        private void Init(string url, string username, string password = null, string apikey = null, bool? disableSslVerification = null, Dictionary<string, string> headers = null)

```

2021-10-22 20:38 UTC, mediumTaj approved these changes
👍 Looks good Thank you Nan!!

2021-10-22 20:42 UTC, merged